chore: Initial Flutter project setup

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,21 +1,21 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-branch="$(git rev-parse --abbrev-ref HEAD)";
-commit_regex='((CDW-)([1-9][0-9])|((feat|fix|chore|refactor|style|test|docs)(((\w{0,15})))?))(:.\S.*)';
-error_msg="Aborting commit. Your commit message format is invalid, please check the references."
-commit_message="$1";
-
-if ! grep -iqE "$commit_regex" <<<"${commit_message}"; then
-echo "$error_msg" >&2
-exit 1
+if [ -z "$1" ]; then
+	echo "Missing argument (commit message). Did you try to run this manually?"
+	exit 1
 fi
 
-if [ "$branch" = "master" ]; then
-echo "You can't commit directly to master branch"
-exit 1
+commitTitle="$(cat $1 | head -n1)"
+
+# ignore merge requests
+if echo "$commitTitle" | grep -qE "^Merge branch \'"; then
+	echo "Commit hook: ignoring branch merge"
+	exit 0
 fi
 
-if [ "$branch" = "develop" ]; then
-echo "You can't commit directly to develop branch"
-exit 1
+# check semantic versioning scheme
+if ! echo "$commitTitle" | grep -qE '^(?:feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'; then
+	echo "Your commit title did not follow semantic versioning: $commitTitle"
+	echo "Please see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format"
+	exit 1
 fi
